import { useState, useRef, useEffect } from 'react';
import { api } from './api.js';
import { Spinner, ChatMsg } from './components.jsx';

// ── Base modal ────────────────────────────────────────────────────────────────
export function Modal({ title, sub, onClose, wide, children }) {
  return (
    <div className="overlay" onClick={e => e.target.classList.contains('overlay') && onClose()}>
      <div className={`modal${wide?' wide':''}`}>
        <div className="modal-hd">
          <div>
            <div className="modal-title">{title}</div>
            {sub && <div className="modal-sub">{sub}</div>}
          </div>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>
        {children}
      </div>
    </div>
  );
}

// ── Ghost Developer ───────────────────────────────────────────────────────────
export function GhostModal({ file, author, repoPath, onClose }) {
  const [messages, setMessages] = useState([
    { role:'bot', text:"I'm ready. Ask me anything about this file — why it was built this way, what's dangerous to change, what you need to know before touching it." }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const chatRef = useRef(null);

  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight; }, [messages]);

  async function ask() {
    const q = input.trim();
    if (!q) return;
    setInput('');
    setMessages(m => [...m, { role:'user', text:q }]);
    setLoading(true);
    const res = await api.ghost(q, file, repoPath, author);
    setLoading(false);
    setMessages(m => [...m, { role:'bot', text: res?.answer ? res.answer.replace(/\n/g,'<br>') : `⚠ ${res?.error||'Connect IBM Bob CLI for Ghost Developer responses.'}` }]);
  }

  return (
    <Modal title="👻 Ghost Developer Mode" sub={`Responding as author of: ${file} (${author})`} onClose={onClose}>
      <div className="ghost-chat" ref={chatRef}>
        {messages.map((m,i) => <ChatMsg key={i} role={m.role}>{m.text}</ChatMsg>)}
        {loading && <div className="msg bot"><div className="msg-lbl">IBM Bob</div><div className="bubble"><Spinner/>Consulting knowledge docs…</div></div>}
      </div>
      <div className="ghost-row">
        <input className="ghost-input" value={input}
          onChange={e=>setInput(e.target.value)}
          onKeyDown={e=>e.key==='Enter'&&ask()}
          placeholder="Why did you build it this way? What's dangerous to change?"/>
        <button className="btn btn-p" onClick={ask} disabled={loading}>Ask</button>
      </div>
    </Modal>
  );
}

// ── Knowledge Doc ─────────────────────────────────────────────────────────────
export function DocModal({ file, repoPath, onClose }) {
  const [content, setContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [loadingMsg, setLoadingMsg] = useState('IBM Bob is reading the file...');

  useEffect(() => {
    const messages = [
      'IBM Bob is reading the file...',
      'Analyzing code structure...',
      'Understanding dependencies...',
      'Generating knowledge document...',
      'Almost done...',
    ];
    let i = 0;
    const interval = setInterval(() => {
      i = (i + 1) % messages.length;
      setLoadingMsg(messages[i]);
    }, 8000);

    api.generateDoc(file, repoPath).then(res => {
      clearInterval(interval);
      setLoading(false);
      setContent(res?.answer ||
        `⚠ ${res?.error || 'Connect IBM Bob CLI to generate knowledge transfer documents.'}`);
    });

    return () => clearInterval(interval);
  }, [file, repoPath]);

  return (
    <Modal title="📄 Knowledge Transfer Document" sub={`Generated by IBM Bob — ${file}`} onClose={onClose} wide>
      <div className="doc-content" id="doc-content-text">
        {loading ? <><Spinner/> {loadingMsg}</> :
          (content && (content.includes('timed out') || content.includes('too long')))
            ? '⏳ Bob is analyzing the file. This can take 1-2 minutes for complex files. Try clicking Generate Knowledge Doc again.'
            : content}
      </div>
      <div style={{marginTop:12,display:'flex',gap:8}}>
        <button className="btn btn-c" onClick={() => {
          const text = document.getElementById('doc-content-text')?.innerText
            || document.getElementById('doc-content-text')?.textContent
            || '';
          navigator.clipboard.writeText(text)
            .then(() => alert('Copied to clipboard!'))
            .catch(() => {
              const el = document.createElement('textarea');
              el.value = text;
              document.body.appendChild(el);
              el.select();
              document.execCommand('copy');
              document.body.removeChild(el);
              alert('Copied!');
            });
        }}>Copy</button>
        <button className="btn btn-g" onClick={onClose}>Close</button>
      </div>
    </Modal>
  );
}

// ── Issue Explain ─────────────────────────────────────────────────────────────
export function IssueModal({ title, files, repoPath, onClose }) {
  const [content, setContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [loadingMsg, setLoadingMsg] = useState('IBM Bob is analyzing the architectural issue...');

  useEffect(() => {
    const messages = [
      'IBM Bob is analyzing the architectural issue...',
      'Reading affected files...',
      'Understanding impact...',
      'Generating recommendations...',
      'Almost done...',
    ];
    let i = 0;
    const interval = setInterval(() => {
      i = (i + 1) % messages.length;
      setLoadingMsg(messages[i]);
    }, 8000);

    api.explainIssue(title, files, repoPath).then(res => {
      clearInterval(interval);
      setLoading(false);
      setContent(res?.answer || `⚠ ${res?.error||'Connect IBM Bob CLI for detailed architectural analysis.'}`);
    });

    return () => clearInterval(interval);
  }, [title, files, repoPath]);

  return (
    <Modal title="🤖 Bob's Analysis" sub={title} onClose={onClose} wide>
      <div className="doc-content">
        {loading ? <><Spinner/> {loadingMsg}</> : content}
      </div>
    </Modal>
  );
}